kind: pipeline
name: default

steps:
  - name: build
    image: registry:5000/node-build
    commands:
      - yarn
      - yarn compile
      - yarn publish --access public --registry https://registry.npmjs.org
