services:
  prometheus:
    image: prom/prometheus
    networks:
      - grafana
      - prom_int
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    hostname: prometheus
    container_name: prometheus
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    hostname: node_exporter
    networks:
      - prom_int
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    pid: host
    restart: always

  cadvisor:
    image: google/cadvisor
    hostname: cadvisor
    container_name: cadvisor
    restart: always
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    networks:
      - prom_int
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus:
    external: true
networks:
  grafana:
    external: true
  prom_int:
    driver: bridge
    internal: true
